name = "ConnesLean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ConnesLean"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[require]]
name = "LSpec"
scope = "argumentcomputer"
rev = "7f5bb9de3aab89c2c24a1c917b17d9b75e6f220e"

[[lean_lib]]
name = "ConnesLean"

[[lean_lib]]
name = "test"
globs = ["test"]

[[lean_lib]]
name = "lspec"
globs = ["lspec"]

[[lean_exe]]
name = "connes_lspec"
root = "lspec.Main"
